version: '3.0'
services:
  db-init:
    network_mode: "host"
    image: postgres:13.7
    env_file:
      - .env_file
    environment:
      PGAPPNAME: psql
    volumes:
      - ./scripts/init-db.sql:/init-db.sql
    command: [ "psql", "-f", "init-db.sql", "-d", "postgres" ]
  pgbench-init:
    network_mode: "host"
    image: postgres:13.7
    env_file:
      - .env_file
    environment:
      PGAPPNAME: pgbench-init
    volumes:
      - ./scripts/write-benchmark.sql:/write-benchmark.sql
      - ./scripts/pgbench-init.sh:/init.sh
    command:
      [
        "/init.sh"
      ]
  pgbench-write:
    network_mode: "host"
    image: postgres:13.7
    env_file:
      - .env_file
    environment:
      PGAPPNAME: pgbench
    volumes:
      - ./scripts/write-benchmark.sql:/write-benchmark.sql
      - ./scripts/pgbench-write.sh:/write.sh
    command:
      [
        "/write.sh"
      ]
  pgbench-read:
    network_mode: "host"
    image: postgres:13.7
    env_file:
      - .env_file
    environment:
      PGAPPNAME: pgbench
    volumes:
      - ./scripts/read-benchmark.sql:/read-benchmark.sql
      - ./scripts/pgbench-read.sh:/read.sh
    command:
      [
        "/read.sh"
      ]
  pgbench-read-simple:
    network_mode: "host"
    image: postgres:13.7
    env_file:
      - .env_file
    environment:
      PGAPPNAME: pgbench
    volumes:
      - ./scripts/read-simple.sql:/read-simple.sql
      - ./scripts/pgbench-read-simple.sh:/read-simple.sh
    command:
      [
        "/read-simple.sh"
      ]
